name: api

channels:
  - rdkit
  - defaults
  - conda-forge

dependencies:
  - python=3.7
  - rdkit::rdkit=2020.09.1.0
  - tmap::tmap
  - mhfp
  # The EGFR and BACE1 models require < 0.22
  - scikit-learn==0.21.3
  # - scikit-learn>=0.22
  - numpy>=1.15.4
  - flask
  - flask-smorest
  - flask-cors
  - flask-caching
  - curl
  - unzip
  - tensorflow-gpu==1.15
  # umap-learn >= 0.5 requires scikit >= 0.22
  - conda-forge::umap-learn==0.4.6
  - requests
